matrix:
  include:
  - os: linux
    dist: xenial
  - os: linux
    dist: trusty
  - os: linux
    dist: precise
  - os: osx
    osx_image: xcode11
  - os: osx
    osx_image: xcode10.2
  - os: osx
    osx_image: xcode9.4
  - os: osx
    osx_image: xcode8.3
  - os: osx
    osx_image: xcode7.3

script:
  - source conda-ci install
  - conda list
  - source conda-ci install-conda-build
  - conda build recipe
