matrix:
  include:
  - os: linux
    dist: xenial
  - os: linux
    dist: trusty
  - os: osx
    osx_image: xcode11
  - os: osx
    osx_image: xcode10.2
  - os: osx
    osx_image: xcode9.4
  - os: osx
    osx_image: xcode8.3
  - os: osx
    osx_image: xcode7.3
  - os: linux
    env: OPT="--prefix $HOME/test/prefix"
  - os: osx
    env: OPT="--prefix $HOME/test/prefix"

script:
# install conda
  - source conda-ci install $OPT
  - echo CONDA_PREFIX is "$CONDA_PREFIX"
# check if conda executable is in the right place
  - if [[ -n "$OPT" ]]; then
        ls "$OPT"/bin/conda ;
    else
        ls "$HOME"/opt/bin/conda ;
    if
  - conda list
  - source conda-ci install-conda-build
  - conda list
# build test recipe
  - conda build recipe
  - ls "$CONDA_PREFIX"/conda-bld/$TRAVIS_OS_NAME-64/testme*bz2
