name: CI

on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install
      run: |
        source conda-ci install $OPT

    - name: Test
      run: |
        source activate base
        echo CONDA_PREFIX is "$CONDA_PREFIX"
        conda list
        source conda-ci install-conda-build
        conda list
        conda build -c conda-forge recipe
        ls "$CONDA_PREFIX"/conda-bld/*-64/testme*bz2
